# Generated by Django 3.2.9 on 2021-12-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211202_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='Class',
            field=models.CharField(max_length=30, verbose_name='Класс сериала'),
        ),
    ]
